### ISSUE TITLE
Getting black screen while applying SSR in build.

### ISSUE THREAD

**Issue by fueldown** [kode80/kode80SSR#11]
Hey Kode80,
I was so stoked to try out your implementation of SSR with Unity 5 and it works absolute marvels in the editor, but when I build it, it just renders black screen. Not only that, but when I switch to another real-time lit (with pre-computed GI) scene (which doesn't have SSR) from black screen, there are no shadows in the scene. Not a single clue why this happens as I am programmer with Zero knowledge of graphics pipeline. 

As to give more info about the scene, it is a arch-viz project. I have SSR as first effect on camera, then anti-aliasing and lastly bloom. Please help me, coz I need reflections (obviously, being an arch-viz project) to work properly. Thank you. I hope you will have some guidelines for me to set up the scene well.

**Comment by KenzieMac130** [comment]
Try looking in the Closed Issues, you might be having the same problem I had.

**Comment by kode80** [comment]
Yep, this sounds like you haven't put the shaders into your /assets/resources folder, which is required so that Unity knows to export them when you do a stand alone build,
