### ISSUE TITLE
Why the sky does not reflect?

### ISSUE THREAD

**Issue by jessyoblio** [kode80/kode80SSR#8]
I noticed that the sky does not reflect on the materials. I don't know if in your plans you want implement your SSR Shader. But ,probably, it's necessary for a real calculation of the reflections. It's too much for me write this, but i want help you. Anyway, Great work!

Reference ( Sky light from windows ):
http://abload.de/img/realisticrendering201gssdm.jpg

**Comment by kode80** [comment]
This is due to sky boxes having no depth which makes them difficult to reflect via SSR. Your best bet would be to use a global cube map which should then appear when SSR picks up no reflections.
