### ISSUE TITLE
SSR buffer does not handle HDR

### ISSUE THREAD

**Issue by kode80** [kode80/kode80SSR#9]
Currently reflections are not using full HDR range. I'm opening this issue as a reminder to look into the possibility of implementing HDR reflections.

**Comment by KenzieMac130** [comment]
Hello I just added HDR support into a separate branch and made a Pull Request.

**Comment by kode80** [comment]
Thanks for this, reflections look a lot better in HDR mode now! 

I've merged along with a minor edit to automatically use HDR if it is enabled on the camera rather than using a separate property on the SSR script.
